site_name: Denis Markushin
site_url: https://denis-markushin.github.io/

theme:
  name: material
  features:
    - navigation.indexes
    - header.autohide

plugins:
  - search
  - tags
  - blog:
      blog_dir: .